### ISSUE TITLE
Rework application gallery

### ISSUE THREAD

**Issue by chrisduerr** [chrisduerr/catacomb#19]
The current application gallery behaves somewhat awkwardly and doesn't ideally maximize space usage. So instead a slightly different design approach should be taken.

Android / Gnome Mobile might be more clutter-free application galleries to look at instead:

![Android](https://cdn.mos.cms.futurecdn.net/BasbZAGLR2d4CSkCKqeni4.jpg)

[Gnome Mobile](https://user-images.githubusercontent.com/8886672/188783623-33a5529b-332c-42c7-90da-085783c3efbb.webm)

**Comment by kchibisov** [comment]
I'd also add a note that you should render during preview and not freeze the apps. Since it looks a bit weird and doesn't allow on-demand progress checking without explicit focus.

**Comment by chrisduerr** [comment]
> I'd also add a note that you should render during preview and not freeze the apps. Since it looks a bit weird and doesn't allow on-demand progress checking without explicit focus.

That's an interesting point, I've explicitly decided **against** this just to prevent pointless redraws originally.

Would you suggest to just redraw the one "center" application in the gallery continuously, or redraw every application in the gallery? Or maybe a mix drawing N windows to the left/right.

**Comment by kchibisov** [comment]
I'd draw all visible windows.

**Comment by chrisduerr** [comment]
Define "visible". So basically the center one and the ones to the left/right if we're looking at android/gnome?

**Comment by kchibisov** [comment]
Yes.
